# CI De Nível 1 - Disparo manual a partir de um clique no botão "Build"

# nome do 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/trigger)
#gatilho de execução manual = workflow_dispatch

on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# trabalho/tarefa dentro do pipeline = job
jobs:
  # nome do job
  e2e-test:
    # maquina onde o job será executado
    runs-on: ubuntu-latest

    # condicional - if
    # `${ expressao }`
    # == comparação

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Clone do repositório
      - uses: actions/checkout@v4

      # Instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # Instalação das dependências
      - name: Instalando Dependências
        run: yarn

      # Instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # Execução dos testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report
