# CI De Nível 04 - Disparo dos testes  dentro do pipeline de DEV

# nome do 'pipeline'
name: 'Execução Integrada'

# regras de disparo (gatilhos/trigger)
#gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalho/tarefa dentro do pipeline = job
jobs:
  inspecao:
    runs-on: ubuntu-latest # maquina onde o job será executado

    steps: # lista de passos/tarefas
      - uses: actions/checkout@v4 # checkout do repositório

      - name: Instalando Yarn # nome do passo
        run: npm install -g yarn # comando a ser executado

      - name: Instalando dependencias # nome do passo
        run: yarn # comando a ser executado

      - name: Checando padronizacao do codigo # nome do passo
        run: yarn lint # comando a ser executado

  unidade:
    # maquina onde o job será executado
    runs-on: ubuntu-latest
    # lista de passos/tarefas
    steps:
      # checkout do repositório
      - uses: actions/checkout@v4
      # instalando o yarn (nodejs) geralmente ja vem instalado (opcional)
      - name: Instalando Yarn
        run: npm install -g yarn
      # instalando as dependencias
      - name: Instalando dependencias
        run: yarn # comando a ser executado
      # executando os testes de unidade
      - name: Executando Testes de Unidade
        run: yarn test

  e2e-test:
    runs-on: ubuntu-latest # maquina onde o job será executado

    steps:
      - uses: actions/checkout@v4 # checkout do repositório

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Yarn # Instalando o yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Instalando Playwright # Instalando o playwright
        run: yarn playwright install

      - name: Executando Testes E2E
        run: yarn run e2e

      - name: Uploading Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} # condicional - se o job nao for cancelado
        with:
          name: relatorio-e2e # nome do arquivo
          path: ./playwright-report # caminho do arquivo

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy simulation
        run: echo 'Deploy application with success!' # mensagem a ser exibida
